### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by sith-on-mars** [FedoraQt/QAdwaitaDecorations#21]
Could we have Flatpak support for this as well? It would be massively beneficial since Flatpak is getting more and more popular nowadays.

**Comment by grulja** [comment]
Yes, definitely, I will try to bring this to Flathub as soon as possible. I need to do also some changes to QGnomePlatform and KDE runtime for that so it works out of the box.

**Comment by grulja** [comment]
Submitted here: https://github.com/flathub/flathub/pull/4556

**Comment by sith-on-mars** [comment]
Thanks a lot for supporting Flatpak. However, is there any instruction for enabling QAdwaitaDecorations for Flatpak apps? I tried `flatpak override --env=QT_WAYLAND_DECORATION=adwaita`, but it doesn't do anything.

**Comment by grulja** [comment]
This was only Qt6 build. I'm now doing Qt5 version.

**Comment by grulja** [comment]
Can you try build from here https://github.com/flathub/org.kde.WaylandDecoration.QAdwaitaDecorations/pull/1? It seem to fixed the issue for me.

**Comment by CoolingTool** [comment]
Yes it fixed the issue. Thank you

**Comment by LSeelig** [comment]
The latest update is yet to release on Flatpak. It's not been very long (a week), but I don't know if the process requires review and is or isn't automatic after pushing an update.

**Comment by grulja** [comment]
> The latest update is yet to release for Flatpaks. It's not been very long (a week), but I don't know if the process requires review and is or isn't automatic after pushing an update.

I did push updated to Flathub when I did the release. What Qt version is missing?

**Comment by LSeelig** [comment]
> > The latest update is yet to release for Flatpaks. It's not been very long (a week), but I don't know if the process requires review and is or isn't automatic after pushing an update.
> 
> I did push updated to Flathub when I did the release. What Qt version is missing?

None anymore. To my knowledge, it is resolved.
