### ISSUE TITLE
Larger cursor in qt5 windows with qadwaitadecorations-qt5 - Arch linux

### ISSUE THREAD

**Issue by coxackie** [FedoraQt/QAdwaitaDecorations#39]
As the title says, using `qadwaitadecorations-qt5` in Arch linux results in the mouse cursor changing size (magnifying) when moving inside qt5 windows. Noticed it with `kid3-qt` and `flacon`, but from what I understand it is a general problem. Let me know what other details I can provide.

**Comment by grulja** [comment]
Does it happen when you use `QT_WAYLAND_DECORATION=bradient`?

**Comment by grulja** [comment]
> hmmmm... yes, it does, in fact.

Then it's a bug (or some misconfiguration) in QtWayland and not in decorations.
