### ISSUE TITLE
Inconsistent Window Titles

### ISSUE THREAD

**Issue by LSeelig** [FedoraQt/QAdwaitaDecorations#51]
I don't know if this is fixable. Window titles in GTK apps are almost always displayed with the bold system font, but QT apps have different, often non-bold title conventions, even inside of the Adwaita window decorations. Can this plugin mandate the font and bold format, or even offer some way to force the application's name to display?
GTK:
![image](https://github.com/FedoraQt/QAdwaitaDecorations/assets/37001137/aaca45dc-7d19-499d-8ee9-8a594dd16beb)
QAdwaitaDecorations:
![Screenshot from 2024-01-27 13-57-26](https://github.com/FedoraQt/QAdwaitaDecorations/assets/37001137/441a7614-e4e0-40d6-a95e-d0a91f315476)

**Comment by LSeelig** [comment]
There's also the new LibAdwaita 1.4 color change from grey to white in light mode.

**Comment by grulja** [comment]
Can you please test https://github.com/FedoraQt/QAdwaitaDecorations/pull/54?
