### ISSUE TITLE
Buttons have more horizontal padding on the right than standard Adwaita header bars

### ISSUE THREAD

**Issue by TheBoctor** [FedoraQt/QAdwaitaDecorations#53]
The screenshots in issue #51 already demonstrate this, but I figured it would be better etiquette to open a separate issue. The QAdwaitaDecorations buttons are further to the left (they have more padding on their right), compared to the standard GTK header bars. Though this is a visual nitpick, it may have ergonomic or muscle memory implications for a user.

I can compile again and take more screenshots, if required.

**Comment by grulja** [comment]
Can you please test with https://github.com/FedoraQt/QAdwaitaDecorations/pull/55?

**Comment by TheBoctor** [comment]
Thanks so much for these changes. The spacing and alignment with #55 are nearly identical to libadwaita apps, though there is still a tiny difference, judging from the positioning of the close/maximize buttons in this screenshot.

![image](https://github.com/FedoraQt/QAdwaitaDecorations/assets/45834980/22fd0357-c855-42ed-8c8c-ae0f5839b8f2)

(Top to bottom: A Qt dialog, a libadwaita app, an XWayland app, and Firefox with its "compact" top bar height. GTK3/XWayland apps here are using the unofficial adw-gtk3 theme, to show them with libadwaita-style buttons.)

**Comment by grulja** [comment]
Can you test it now?

**Comment by TheBoctor** [comment]
Here are the same applications, against the same screen edge, with the new changes in `spacing`. I've made sure to include both the dark and light colors, this time.
![image](https://github.com/FedoraQt/QAdwaitaDecorations/assets/45834980/469c9d3c-1896-4ede-9cd2-b6a4564a3d8f)
![image](https://github.com/FedoraQt/QAdwaitaDecorations/assets/45834980/ef74903a-1745-47c8-a38c-ad3feb7f52a2)

**Comment by grulja** [comment]
It looks like in your case only the "minimize" button is 1px off. I'm now testing it on 4k screen with 2x scaling and I have the "minimize" button 2px off and the "maximize" button 1px off. Not sure how to solve this.

**Comment by grulja** [comment]
Now testing on an external screen with QHD and 1,25x scaling I end up with having same result as you, where the minimize button looks like it's 1px off. I think I'm going to merge it as it is now. It's not 1:1, but it's barely noticable.

**Comment by TheBoctor** [comment]
Sounds good. Some popular applications like Firefox (and all XWayland applications with Mutter decorations) still deviate more from the exact Libadwaita button alignment, so this shouldn't be easy to spot.
