### ISSUE TITLE
Can this be used on Xorg?

### ISSUE THREAD

**Issue by notevenaperson** [FedoraQt/QAdwaitaDecorations#57]
So, setting `QT_WAYLAND_DECORATION=adwaita` did nothing, as expected by the big WAYLAND in the name.

To arrive here I just followed a lineage of unmaintained projects that ends here, so far. **QAdwaitaDecorations** replaces [QAdwaitaPlatform](https://github.com/urFate/QAdwaitaPlatform) replaces [QGnomePlatform](https://github.com/FedoraQt/QGnomePlatform), or at least that's the direction developers point to before archiving. 

I didn't get the chance to try those ancestor projects, but I had the impression they support Xorg? Is QAdwaitaDecorations the one to not support Xorg? I'm not saying you have the responsibility to, I just want to know. The project just before this one (QAdwaitaPlatform) states that it is unmaintained due to "irrelevance". I want to know if this is really the direction 🛣️.

**Comment by taoky** [comment]
This is unnecessary on Xorg -- window manager will give a SSD (server-side decoration) for programs without a decoration.

https://jgrulich.cz/2023/08/22/qt-theming-in-fedora-workstation/ and relevant posts might explain the reason of QGnomePlatform's deprecation.
