### ISSUE TITLE
Some buttons using GTK3 style

### ISSUE THREAD

**Issue by sith-on-mars** [FedoraQt/QAdwaitaDecorations#64]
My Qt app are installed via Flatpak, which come with QAdwaitaDecorations dependency automatically.

Some buttons of Qt apps still look like using legacy GTK 3. For example, 

Tor Browser Launcher:

![image](https://github.com/FedoraQt/QAdwaitaDecorations/assets/37974764/ad77dedb-3541-473b-8ea1-3203ebcccb1c)

Qpdf Tools:

![image](https://github.com/FedoraQt/QAdwaitaDecorations/assets/37974764/03c1edea-8b6e-4d74-88ba-f5fbd7e22b24)

**Comment by grulja** [comment]
Looks like you are talking about Adwaita-qt, which is is different and already a dead project. This project is only about client-side windows decorations. Adwaita-qt is still GTK3 based and it's not going to be updated as the project is now unmaitained.
