### ISSUE TITLE
Transparent bottom border, possibly related to fractional scaling

### ISSUE THREAD

**Issue by likeaross** [FedoraQt/QAdwaitaDecorations#65]
I can only assume this is an artifact with fractional scaling (mine is set to 125%)... when resizing the height of a window, certain steps will add a transparent line to the bottom border.

![image](https://github.com/FedoraQt/QAdwaitaDecorations/assets/483960/a06e57c0-5857-4584-b3d0-5ebc39a392f2)

[example.webm](https://github.com/FedoraQt/QAdwaitaDecorations/assets/483960/fdf15154-7f09-4327-85fb-9bc527362a4e)

**Comment by grulja** [comment]
I believe this is fixed with https://github.com/FedoraQt/QAdwaitaDecorations/pull/70, https://github.com/FedoraQt/QAdwaitaDecorations/pull/75 and https://github.com/FedoraQt/QAdwaitaDecorations/pull/77.
