### ISSUE TITLE
Make it work on Plasma Wayland

### ISSUE THREAD

**Issue by saihaze** [FedoraQt/QAdwaitaDecorations#74]
It seems that the decorations only apply on GNOME. Is it possible to make it also work on Plasma?

**Comment by grulja** [comment]
It applies only where Qt decoration plugin is used, which is not the case of KWin on Plasma.

**Comment by saihaze** [comment]
> It applies only where Qt decoration plugin is used, which is not the case of KWin on Plasma.

I see. Thank you!
